apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-micronaut
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/{username}/helloworld-micronaut
            env:
            - name: TARGET
              value: "Micronaut Sample v1"
